// Exemplos de dados para testes (quando API not disponível)

export const carrosExemplo = [
    {
        id: 1,
        marca: 'Toyota',
        modelo: 'Corolla',
        ano: 2023,
        preco: '145000.00',
        cor: 'Prata',
        descricao: 'Carro em perfeito estado, revisado. Apenas 5.000 km rodados. Completo e com som premium.',
    },
    {
        id: 2,
        marca: 'Honda',
        modelo: 'Civic',
        ano: 2023,
        preco: '155000.00',
        cor: 'Preto',
        descricao: 'Civic Sport impecável. Documentação em dia. Pneus novos. Perfeito para quem busca qualidade.',
    },
    {
        id: 3,
        marca: 'Ford',
        modelo: 'Focus',
        ano: 2022,
        preco: '120000.00',
        cor: 'Branco',
        descricao: 'Focus em ótimas condições. Motor à gasolina. Direção eletrônica. Vidros e travas.',
    },
    {
        id: 4,
        marca: 'Volkswagen',
        modelo: 'Golf',
        ano: 2023,
        preco: '160000.00',
        cor: 'Azul',
        descricao: 'Golf 1.4 TSI. Carro europeu de qualidade. Bem cuidado. Lindo!',
    },
    {
        id: 5,
        marca: 'Hyundai',
        modelo: 'HB20',
        ano: 2021,
        preco: '75000.00',
        cor: 'Vermelho',
        descricao: 'HB20 popular e econômico. Perfeito para cidades. Consumo baixo.',
    },
    {
        id: 6,
        marca: 'Chevrolet',
        modelo: 'Onix',
        ano: 2022,
        preco: '80000.00',
        cor: 'Prata',
        descricao: 'Onix confortável e espaçoso. Ideal para famílias. Custo-benefício excelente.',
    },
    {
        id: 7,
        marca: 'BMW',
        modelo: 'X1',
        ano: 2024,
        preco: '280000.00',
        cor: 'Preto',
        descricao: 'BMW X1 de luxo. Carro premium com todos os equipamentos. Impecável.',
    },
    {
        id: 8,
        marca: 'Mercedes-Benz',
        modelo: 'C-Class',
        ano: 2023,
        preco: '320000.00',
        cor: 'Branco',
        descricao: 'Mercedes-Benz C-Class. Elegância e conforto. Motor turbo. Carro de executivo.',
    },
    {
        id: 9,
        marca: 'Fiat',
        modelo: 'Argo',
        ano: 2022,
        preco: '70000.00',
        cor: 'Laranja',
        descricao: 'Fiat Argo prático e barato. Ótimo custo-benefício. Popular entre famílias.',
    },
    {
        id: 10,
        marca: 'Renault',
        modelo: 'Kwid',
        ano: 2021,
        preco: '65000.00',
        cor: 'Verde',
        descricao: 'Renault Kwid econômico. Carro compacto. Fácil de estacionar. Combustível barato.',
    },
];
